version: 2

before:
  hooks:
    - npm --prefix web ci
    - npm --prefix web run build

builds:
  - id: templatr-setup
    main: .
    binary: templatr-setup
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    overrides:
      - goos: windows
        goarch: amd64
        ldflags:
          - -s -w -H windowsgui
          - -X main.version={{.Version}}
          - -X main.commit={{.ShortCommit}}
          - -X main.date={{.Date}}
      - goos: windows
        goarch: arm64
        ldflags:
          - -s -w -H windowsgui
          - -X main.version={{.Version}}
          - -X main.commit={{.ShortCommit}}
          - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "templatr-setup_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: rohan-bhautoo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    name: templatr-setup
    homepage: "https://templatr.io/tools/setup"
    description: "Template setup and dependency installer for Templatr templates"
    license: "MIT"
    install: |
      bin.install "templatr-setup"

scoops:
  - repository:
      owner: rohan-bhautoo
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    name: templatr-setup
    homepage: "https://templatr.io/tools/setup"
    description: "Template setup and dependency installer for Templatr templates"
    license: "MIT"

winget:
  - name: templatr-setup
    publisher: Templatr
    short_description: "Template setup and dependency installer"
    homepage: "https://templatr.io/tools/setup"
    license: "MIT"
    repository:
      owner: rohan-bhautoo
      name: winget-pkgs
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
