name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: input
    id: version
    attributes:
      label: Version
      description: Run `templatr-setup version` and paste the output
      placeholder: "templatr-setup 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      options:
        - Direct download
        - Homebrew
        - Scoop
        - winget
        - Built from source

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `templatr-setup ...`
        2. Upload manifest file
        3. Click Install
        4. See error

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant logs (`templatr-setup logs` to view)
      render: shell
